### PR TITLE
Use `release-2.8` for the generator

### PR DESCRIPTION
**Pull request by dhaiducek**

### CODE REVIEW

**Comment by dhaiducek** [comment]
/hold for:
- https://github.com/stolostron/policy-grc-squad/pull/58
- https://github.com/openshift/release/pull/38262/files

**Review by JustinKuli — APPROVED** [review]

**Review by mikeshng — APPROVED** [review]
/approve

/lgtm

**Comment by dhaiducek** [comment]
Sorry for the churn--I neglected to update `Dockerfile.prow` correctly. Should be good now.

**Review by mikeshng — APPROVED** [review]
/approve

/lgtm

**Comment by dhaiducek** [comment]
The GitHub Action isn't kicking off, even after restarts. Closing and reopening to see whether it resolves.
image

**Comment by dhaiducek** [comment]
@mikeshng It looks like Ubuntu 18 may not exist as an available runner?
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by dhaiducek** [comment]
Rebased--thanks for the update!

I'll unhold this PR once fast-forwarding to `release-2.8` is complete in the policy generator repo (probably later today).

**Pull request merged**
