### PR TITLE
Red Hat Konflux update multicluster-operators-subscription-acm-213

### PR DESCRIPTION
**Pull request by xiangjingli**
* [X] I have taken backward compatibility into consideration.

### CODE REVIEW

**Comment by xiangjingli** [comment]
@dhaiducek  FYI, the image build in the konflux pipeline still failed. I noticed the new error
```
go: go.mod requires go >= 1.22.10 (running go 1.22.9; GOTOOLCHAIN=local)
```
It seem the go version used in the repo is higher

**Comment by dhaiducek** [comment]
Shoot. I was wondering if I should have put 1.22.0 to be safe--I thought it could handle it. I'll bump the go.mod down.

**Comment by dhaiducek** [comment]
PR opened:
- https://github.com/open-cluster-management-io/multicloud-operators-subscription/pull/416

**Comment by dhaiducek** [comment]
Oh my goodness. It worked! 😄 

Only thing is it looks like there's an environment variable somewhere that's setting the Helm version to "1.22", but I'm not sure it's worth fixing at this point. 🙂 

```
GO111MODULE=on CGO_ENABLED=1 go build  -trimpath -tags '' -ldflags '-w -s 
-X helm.sh/helm/v3/internal/version.version=1.22
...
-o '/helm/helm/bin'/helm ./cmd/helm
```

**Comment by xiangjingli** [comment]
@dhaiducek Everything is good after I re-run the unit test. so I merged the PR to release-2.13 branch, really appreciate your contributions! 

For the helm version set to 1.22 issue. It is up to you to fix it or not as the built helm cli is not used by appsub.  I guess we may live with it if nothing is broken in the later QE e2e test automation.

**Comment by dhaiducek** [comment]
> @dhaiducek Everything is good after I re-run the unit test. so I merged the PR to release-2.13 branch, really appreciate your contributions!
> 
> For the helm version set to 1.22 issue. It is up to you to fix it or not as the built helm cli is not used by appsub. I guess we may live with it if nothing is broken in the later QE e2e test automation.

Glad it's all working! 🥳 

I agree--I'll probably leave it as-is since I think it's unlikely someone might exec into the container to run `helm version` to verify what the policy generator might be doing. There's a lot of layers above that, so it's pretty minor.

**Pull request merged**
