### PR TITLE
backport fix - kube 1.24 service account token secret changes

### PR DESCRIPTION
**Pull request by xiangjingli**
Signed-off-by: Xiangjing Li <xiangli@redhat.com>

https://github.com/stolostron/backlog/issues/25558

The fix is to backport the fix from main to 2.5 branch for supporting Argocd push model in OCP 4.11 (kube 1.24 core), where the SA secret token is no longer created automatically. As a result, the SA secret token is not listed in the SA. The SA secret is required to search in the same NS

### CODE REVIEW

**Comment by mikeshng** [comment]
@xiangjingli 

`https://github.com/stolostron/policy-generator-plugin/archive/refs/tags/1.7.0.tar.gz`

This file no longer exist that's why the test is failing.

**Comment by mikeshng** [comment]
@xiangjingli I don't know why but https://github.com/stolostron/multicloud-operators-subscription/pull/826 passed. Maybe something wrong with the Prow environment for this PR? Can you try close this PR and recreate it? Maybe rename the branch and push it again and recreate another PR?

**Comment by xiangjingli** [comment]
@mikeshng   Yeah, it looks like a PROW env issue at that time. I will retest it again, if no luck, I will create a new PR. 

BTW, The file exists. `https://github.com/stolostron/policy-generator-plugin/archive/refs/tags/v1.7.0.tar.gz`

**Review by mikeshng — APPROVED** [review]
This code is the same as `main` branch and `release-2.6` branch.

/approve

/lgtm

**Pull request merged**
