### PR TITLE
Update CloneGitRepo

### PR DESCRIPTION
**Pull request by vMaroon**
usingPrimary = false is not placed correctly (does nothing atm)

Signed-off-by: Maroon Ayoub <maroon.ayoub@ibm.com>

### CODE REVIEW

**Comment by mikeshng** [comment]
Thank you for your contribution. Please sign your commit by

```
git commit -s --amend
git push -f ... 
```

**Review by rokej — APPROVED** [review]
Thank you

**Comment by vMaroon** [comment]
@rokej https://github.com/open-cluster-management-io/multicloud-operators-subscription/pull/97

**Comment by vMaroon** [comment]
this got messy ill just re-open

**Pull request closed without merging**
