### PR TITLE
[manual-sync] Generator / base image upgrade

### LINKED ISSUE #1103: 😿 Failed to sync the upstream PRs: #405
🪞 Magic Mirror 🪞 failed to sync the following upstream pull-requests because one or more patches couldn't cleanly apply:
* open-cluster-management-io/multicloud-operators-subscription#405

Syncing is paused for the branch main on stolostron/multicloud-operators-subscription until the issue is manually resolved and this issue is closed.

Syncing error:
```
Error: [magic-mirror-main-1719325716022 6caa72d] performance enhacement on 3500 scale test env (#404)
 Author: Xiangjing Li <55890329+xiangjingli@users.noreply.github.com>
 Date: Mon Jun 24 19:37:38 2024 -0400
Auto-merging build/Dockerfile
CONFLICT (content): Merge conflict in build/Dockerfile
Auto-merging build/Dockerfile.prow
CONFLICT (content): Merge conflict in build/Dockerfile.prow
Auto-merging build/Dockerfile.rhtap
CONFLICT (content): Merge conflict in build/Dockerfile.rhtap
error: could not apply 5aeb0f3... Upgrade: Generator to v1.14.0 / Base image to UBI9 (#405)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```

Commands to recreate the issue:

```
git cherry-pick -x 5aeb0f3f1282395ade691ddf1211d9158db8d244~2..5aeb0f3f1282395ade691ddf1211d9158db8d244 --allow-empty --keep-redundant-commits
```

sad Yoda

### PR DESCRIPTION
**Pull request by dhaiducek**
* [x] I have taken backward compatibility into consideration.

Manual sync:
- https://github.com/open-cluster-management-io/multicloud-operators-subscription/pull/405

Closes #1103

### CODE REVIEW

**Review by mikeshng — APPROVED** [review]

**Comment by dhaiducek** [comment]
@mikeshng I noticed Konflux broke fast-forwarding. Would you like this PR cherry-picked to 2.11 also?

**Comment by mikeshng** [comment]
leaving @xiangjingli to take another quick look. I didn't Lgee2m but it added the Lgee2m label anyways :sweat_smile:

**Comment by mikeshng** [comment]
> @mikeshng I noticed Konflux broke fast-forwarding. Would you like this PR cherry-picked to 2.11 also?

@xiangjingli FYI. I am not sure Dale.

**Comment by dhaiducek** [comment]
> leaving @xiangjingli to take another quick look. I didn't Lgee2m but it added the Lgee2m label anyways 😅

Yeah, approval == lgtm 😅 
ref: https://github.com/openshift/release/blob/bfc11daaadafc888a4263331e9486edc27533702/core-services/prow/02_config/stolostron/_pluginconfig.yaml#L25

**Comment by xiangjingli** [comment]
@mikeshng @dhaiducek Yeah, I will fast forward it to 2.11 once it is in the main branch

**Comment by xiangjingli** [comment]
@dhaiducek I just cherry picked it to release-2.11 branch. Also I created another PR for updating the Docker and Docker.prow to align with your changes.

Please double check the 3 Docker files in the release-2.11 branch when you have a cycle
```
build/Dockfile
build/Dockfile.prow
build/Dockfile.rhtap
```

**Comment by dhaiducek** [comment]
Thanks, @xiangjingli! Looks right to me!

**Pull request merged**
